#!/bin/sh
while read file
do
    fullpath="$(pwd)/$file"
    case "$1" in
        "r")
        name="$(dmenu -p "rename $file to: ")" 2> /dev/null
        if ! [ -z "$name" ]; then
            #mv "$file" "$name"
            mv "$file" "$(dirname $file)/$name"
        fi
        ;;
    esac
done
