#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/code ~/projects ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected -n vim
    tmux send-keys -t $selected_name:vim "vim ." Enter
    tmux new-window -t $selected_name:1 -n $selected_name
    tmux send-keys -t $selected_name:$selected_name "clear;pwd" Enter
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected -n vim
    tmux send-keys -t $selected_name:vim "vim ." Enter
    tmux new-window -t $selected_name:1 -n $selected_name
    tmux send-keys -t $selected_name:$selected_name "clear;pwd" Enter
fi

tmux switch-client -t $selected_name
